sudo: false
language: node_js
node_js:
- '0.12'
- iojs
branches:
  only:
  - webpack
after_success:
- npm run build-prod
- echo -e "Host web187.webfaction.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git remote add deploy ssh://cheung31:${GIT_P}@web187.webfaction.com/home/cheung31/webapps/git/repos/slabby.git
- git push deploy webpack
env:
  global:
    secure: glXs7lg0Mkua2uRbOmCDfT2NoUXfMNZ+kQFbjB80v1H9R5UOS1AUx2fYLk2Xb6i6/PMt3kG72gFYFseIMHdORP8N8B0icQw0QFA1B+0hDn0ZXobb2BH10RsgjSUvLlXXIHXY3tyOWX86GEKXXsWLq/RcmaaZjqm6Ysic6YyXRDA=
