sudo: false
language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
after_success:
- pwd
- ls
- openssl aes-256-cbc -K $encrypted_819d542461eb_key -iv $encrypted_819d542461eb_iv -in ".travis/github_deploy_key.enc" -out "$SSH_FILE" -d
- chmod 600 "$SSH_FILE"
- echo -e "Host web615.webfaction.com\n\tStrictHostKeyChecking no\n\tIdentityFile $SSH_FILE\n" >> ~/.ssh/config
- npm run build-prod
- scp -r dist cheung31@web615.webfaction.com:~/webapps/random/dist
- scp -r css cheung31@web615.webfaction.com:~/webapps/random/css
- scp -r index.html cheung31@web615.webfaction.com:~/webapps/random/index.html
env:
  global:
    secure: JFAHkF5NO6YeVLBW7AP1qlBJ6ivqEFVvammNAmMyC0Ws0AiurL8zWCeNn8iOAxa+bYb9UUZuIms4LZgn6HOjZsbx2Fxus9ynziXK12dFeRpvPBa4PFFYzr3KNJmFfTukPoiHjhZxrAHV5Sm7wRfNaeQVxY+ymdJxlxLsAcg4ReI=
