sudo: false
language: node_js
node_js:
- '0.12'
- iojs
branches:
  only:
  - master
env:
  GH_REF: github.com/cheung31/slabby.git
  GIT_EMAIL: cheung31@gmail.com
  GIT_NAME: Travis CI
  secure: "CMZmMpgjT4j1MfVW1ja1wY5nDioZoDIDT1Rx5gEBu6FfxqYOxAcNvEjjkhYmePowF0tH0DlOVg7YA66T5xiDfBit8iyq7vI6rTlihP9yoPLlDtFrFxhGiZ8EgUSd9GYjylMZArpi6gQpY2v180Z1RZcEHfWCUGoeZf8BKWlDuDI="
after_success:
- npm run build-prod
- git config --global user.email cheung31@gmai.com && echo ${GIT_EMAIL}
- git config --global user.name Travis CI && echo ${GIT_NAME}
- git commit -am "Travis ${TRAVIS_BUILD_NUMBER}" && echo ${TRAVIS_BUILD_NUMBER}
- git remote add deploy https://${GH_TOKEN}@github.com/cheung31/slabby.git && echo ${GH_TOKEN}
- git push deploy production
