sudo: false
language: node_js
node_js:
- '0.12'
- iojs
branches:
  only:
  - master
after_success:
- npm run build-prod
- git remote add deploy https://github.com/cheung31/slabby.git
- git push deploy production
env:
  global:
    GH_REF: github.com/cheung31/slabby.git
    secure: "CMZmMpgjT4j1MfVW1ja1wY5nDioZoDIDT1Rx5gEBu6FfxqYOxAcNvEjjkhYmePowF0tH0DlOVg7YA66T5xiDfBit8iyq7vI6rTlihP9yoPLlDtFrFxhGiZ8EgUSd9GYjylMZArpi6gQpY2v180Z1RZcEHfWCUGoeZf8BKWlDuDI="
