/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/': {
        get: {
            responses: {
                /** OK */
                200: unknown
            }
        }
    }
    '/api_keys': {
        get: {
            parameters: {
                query: {
                    id?: parameters['rowFilter.api_keys.id']
                    description?: parameters['rowFilter.api_keys.description']
                    redirect_url?: parameters['rowFilter.api_keys.redirect_url']
                    created_at?: parameters['rowFilter.api_keys.created_at']
                    updated_at?: parameters['rowFilter.api_keys.updated_at']
                    deleted_at?: parameters['rowFilter.api_keys.deleted_at']
                    /** Filtering Columns */
                    select?: parameters['select']
                    /** Ordering */
                    order?: parameters['order']
                    /** Limiting and Pagination */
                    offset?: parameters['offset']
                    /** Limiting and Pagination */
                    limit?: parameters['limit']
                }
                header: {
                    /** Limiting and Pagination */
                    Range?: parameters['range']
                    /** Limiting and Pagination */
                    'Range-Unit'?: parameters['rangeUnit']
                    /** Preference */
                    Prefer?: parameters['preferCount']
                }
            }
            responses: {
                /** OK */
                200: {
                    schema: definitions['api_keys'][]
                }
                /** Partial Content */
                206: unknown
            }
        }
        post: {
            parameters: {
                body: {
                    /** api_keys */
                    api_keys?: definitions['api_keys']
                }
                query: {
                    /** Filtering Columns */
                    select?: parameters['select']
                }
                header: {
                    /** Preference */
                    Prefer?: parameters['preferReturn']
                }
            }
            responses: {
                /** Created */
                201: unknown
            }
        }
        delete: {
            parameters: {
                query: {
                    id?: parameters['rowFilter.api_keys.id']
                    description?: parameters['rowFilter.api_keys.description']
                    redirect_url?: parameters['rowFilter.api_keys.redirect_url']
                    created_at?: parameters['rowFilter.api_keys.created_at']
                    updated_at?: parameters['rowFilter.api_keys.updated_at']
                    deleted_at?: parameters['rowFilter.api_keys.deleted_at']
                }
                header: {
                    /** Preference */
                    Prefer?: parameters['preferReturn']
                }
            }
            responses: {
                /** No Content */
                204: never
            }
        }
        patch: {
            parameters: {
                query: {
                    id?: parameters['rowFilter.api_keys.id']
                    description?: parameters['rowFilter.api_keys.description']
                    redirect_url?: parameters['rowFilter.api_keys.redirect_url']
                    created_at?: parameters['rowFilter.api_keys.created_at']
                    updated_at?: parameters['rowFilter.api_keys.updated_at']
                    deleted_at?: parameters['rowFilter.api_keys.deleted_at']
                }
                body: {
                    /** api_keys */
                    api_keys?: definitions['api_keys']
                }
                header: {
                    /** Preference */
                    Prefer?: parameters['preferReturn']
                }
            }
            responses: {
                /** No Content */
                204: never
            }
        }
    }
    '/things': {
        get: {
            parameters: {
                query: {
                    id?: parameters['rowFilter.things.id']
                    image_url?: parameters['rowFilter.things.image_url']
                    external_url?: parameters['rowFilter.things.external_url']
                    title?: parameters['rowFilter.things.title']
                    description?: parameters['rowFilter.things.description']
                    content_date?: parameters['rowFilter.things.content_date']
                    created_at?: parameters['rowFilter.things.created_at']
                    updated_at?: parameters['rowFilter.things.updated_at']
                    deleted_at?: parameters['rowFilter.things.deleted_at']
                    external_id?: parameters['rowFilter.things.external_id']
                    type?: parameters['rowFilter.things.type']
                    external_source?: parameters['rowFilter.things.external_source']
                    /** Filtering Columns */
                    select?: parameters['select']
                    /** Ordering */
                    order?: parameters['order']
                    /** Limiting and Pagination */
                    offset?: parameters['offset']
                    /** Limiting and Pagination */
                    limit?: parameters['limit']
                }
                header: {
                    /** Limiting and Pagination */
                    Range?: parameters['range']
                    /** Limiting and Pagination */
                    'Range-Unit'?: parameters['rangeUnit']
                    /** Preference */
                    Prefer?: parameters['preferCount']
                }
            }
            responses: {
                /** OK */
                200: {
                    schema: definitions['things'][]
                }
                /** Partial Content */
                206: unknown
            }
        }
        post: {
            parameters: {
                body: {
                    /** things */
                    things?: definitions['things']
                }
                query: {
                    /** Filtering Columns */
                    select?: parameters['select']
                }
                header: {
                    /** Preference */
                    Prefer?: parameters['preferReturn']
                }
            }
            responses: {
                /** Created */
                201: unknown
            }
        }
        delete: {
            parameters: {
                query: {
                    id?: parameters['rowFilter.things.id']
                    image_url?: parameters['rowFilter.things.image_url']
                    external_url?: parameters['rowFilter.things.external_url']
                    title?: parameters['rowFilter.things.title']
                    description?: parameters['rowFilter.things.description']
                    content_date?: parameters['rowFilter.things.content_date']
                    created_at?: parameters['rowFilter.things.created_at']
                    updated_at?: parameters['rowFilter.things.updated_at']
                    deleted_at?: parameters['rowFilter.things.deleted_at']
                    external_id?: parameters['rowFilter.things.external_id']
                    type?: parameters['rowFilter.things.type']
                    external_source?: parameters['rowFilter.things.external_source']
                }
                header: {
                    /** Preference */
                    Prefer?: parameters['preferReturn']
                }
            }
            responses: {
                /** No Content */
                204: never
            }
        }
        patch: {
            parameters: {
                query: {
                    id?: parameters['rowFilter.things.id']
                    image_url?: parameters['rowFilter.things.image_url']
                    external_url?: parameters['rowFilter.things.external_url']
                    title?: parameters['rowFilter.things.title']
                    description?: parameters['rowFilter.things.description']
                    content_date?: parameters['rowFilter.things.content_date']
                    created_at?: parameters['rowFilter.things.created_at']
                    updated_at?: parameters['rowFilter.things.updated_at']
                    deleted_at?: parameters['rowFilter.things.deleted_at']
                    external_id?: parameters['rowFilter.things.external_id']
                    type?: parameters['rowFilter.things.type']
                    external_source?: parameters['rowFilter.things.external_source']
                }
                body: {
                    /** things */
                    things?: definitions['things']
                }
                header: {
                    /** Preference */
                    Prefer?: parameters['preferReturn']
                }
            }
            responses: {
                /** No Content */
                204: never
            }
        }
    }
    '/rpc/is_api_key': {
        post: {
            parameters: {
                body: {
                    args: {
                        /** Format: character varying */
                        api_key: string
                    }
                }
                header: {
                    /** Preference */
                    Prefer?: parameters['preferParams']
                }
            }
            responses: {
                /** OK */
                200: unknown
            }
        }
    }
}

export interface definitions {
    api_keys: {
        /**
         * Format: uuid
         * @description Note:
         * This is a Primary Key.<pk/>
         * @default extensions.uuid_generate_v4()
         */
        id: string
        /** Format: character varying */
        description?: string
        /** Format: character varying */
        redirect_url?: string
        /**
         * Format: timestamp with time zone
         * @default now()
         */
        created_at?: string
        /** Format: timestamp with time zone */
        updated_at?: string
        /** Format: timestamp with time zone */
        deleted_at?: string
    }
    things: {
        /**
         * Format: uuid
         * @description Note:
         * This is a Primary Key.<pk/>
         * @default extensions.uuid_generate_v4()
         */
        id?: string
        /** Format: character varying */
        image_url?: string
        /** Format: character varying */
        external_url?: string
        /** Format: character varying */
        title?: string
        /** Format: text */
        description?: string
        /** Format: timestamp with time zone */
        content_date?: string
        /**
         * Format: timestamp with time zone
         * @default now()
         */
        created_at?: string
        /**
         * Format: timestamp with time zone
         * @default now()
         */
        updated_at?: string
        /** Format: timestamp with time zone */
        deleted_at?: string
        /** Format: text */
        external_id?: string
        /** Format: text */
        type: string
        /** Format: text */
        external_source: string
    }
}

export interface parameters {
    /**
     * @description Preference
     * @enum {string}
     */
    preferParams: 'params=single-object'
    /**
     * @description Preference
     * @enum {string}
     */
    preferReturn: 'return=representation' | 'return=minimal' | 'return=none'
    /**
     * @description Preference
     * @enum {string}
     */
    preferCount: 'count=none'
    /** @description Filtering Columns */
    select: string
    /** @description On Conflict */
    on_conflict: string
    /** @description Ordering */
    order: string
    /** @description Limiting and Pagination */
    range: string
    /**
     * @description Limiting and Pagination
     * @default items
     */
    rangeUnit: string
    /** @description Limiting and Pagination */
    offset: string
    /** @description Limiting and Pagination */
    limit: string
    /** @description api_keys */
    'body.api_keys': definitions['api_keys']
    /** Format: uuid */
    'rowFilter.api_keys.id': string
    /** Format: character varying */
    'rowFilter.api_keys.description': string
    /** Format: character varying */
    'rowFilter.api_keys.redirect_url': string
    /** Format: timestamp with time zone */
    'rowFilter.api_keys.created_at': string
    /** Format: timestamp with time zone */
    'rowFilter.api_keys.updated_at': string
    /** Format: timestamp with time zone */
    'rowFilter.api_keys.deleted_at': string
    /** @description things */
    'body.things': definitions['things']
    /** Format: uuid */
    'rowFilter.things.id': string
    /** Format: character varying */
    'rowFilter.things.image_url': string
    /** Format: character varying */
    'rowFilter.things.external_url': string
    /** Format: character varying */
    'rowFilter.things.title': string
    /** Format: text */
    'rowFilter.things.description': string
    /** Format: timestamp with time zone */
    'rowFilter.things.content_date': string
    /** Format: timestamp with time zone */
    'rowFilter.things.created_at': string
    /** Format: timestamp with time zone */
    'rowFilter.things.updated_at': string
    /** Format: timestamp with time zone */
    'rowFilter.things.deleted_at': string
    /** Format: text */
    'rowFilter.things.external_id': string
    /** Format: text */
    'rowFilter.things.type': string
    /** Format: text */
    'rowFilter.things.external_source': string
}

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface operations {}

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface external {}
