/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/': {
        get: {
            responses: {
                /** OK */
                200: unknown
            }
        }
    }
    '/things': {
        get: {
            parameters: {
                query: {
                    id?: parameters['rowFilter.things.id']
                    image_url?: parameters['rowFilter.things.image_url']
                    external_url?: parameters['rowFilter.things.external_url']
                    title?: parameters['rowFilter.things.title']
                    description?: parameters['rowFilter.things.description']
                    content_date?: parameters['rowFilter.things.content_date']
                    created_at?: parameters['rowFilter.things.created_at']
                    updated_at?: parameters['rowFilter.things.updated_at']
                    deleted_at?: parameters['rowFilter.things.deleted_at']
                    external_id?: parameters['rowFilter.things.external_id']
                    type?: parameters['rowFilter.things.type']
                    external_source?: parameters['rowFilter.things.external_source']
                    /** Filtering Columns */
                    select?: parameters['select']
                    /** Ordering */
                    order?: parameters['order']
                    /** Limiting and Pagination */
                    offset?: parameters['offset']
                    /** Limiting and Pagination */
                    limit?: parameters['limit']
                }
                header: {
                    /** Limiting and Pagination */
                    Range?: parameters['range']
                    /** Limiting and Pagination */
                    'Range-Unit'?: parameters['rangeUnit']
                    /** Preference */
                    Prefer?: parameters['preferCount']
                }
            }
            responses: {
                /** OK */
                200: {
                    schema: definitions['things'][]
                }
                /** Partial Content */
                206: unknown
            }
        }
        post: {
            parameters: {
                body: {
                    /** things */
                    things?: definitions['things']
                }
                query: {
                    /** Filtering Columns */
                    select?: parameters['select']
                }
                header: {
                    /** Preference */
                    Prefer?: parameters['preferReturn']
                }
            }
            responses: {
                /** Created */
                201: unknown
            }
        }
        delete: {
            parameters: {
                query: {
                    id?: parameters['rowFilter.things.id']
                    image_url?: parameters['rowFilter.things.image_url']
                    external_url?: parameters['rowFilter.things.external_url']
                    title?: parameters['rowFilter.things.title']
                    description?: parameters['rowFilter.things.description']
                    content_date?: parameters['rowFilter.things.content_date']
                    created_at?: parameters['rowFilter.things.created_at']
                    updated_at?: parameters['rowFilter.things.updated_at']
                    deleted_at?: parameters['rowFilter.things.deleted_at']
                    external_id?: parameters['rowFilter.things.external_id']
                    type?: parameters['rowFilter.things.type']
                    external_source?: parameters['rowFilter.things.external_source']
                }
                header: {
                    /** Preference */
                    Prefer?: parameters['preferReturn']
                }
            }
            responses: {
                /** No Content */
                204: never
            }
        }
        patch: {
            parameters: {
                query: {
                    id?: parameters['rowFilter.things.id']
                    image_url?: parameters['rowFilter.things.image_url']
                    external_url?: parameters['rowFilter.things.external_url']
                    title?: parameters['rowFilter.things.title']
                    description?: parameters['rowFilter.things.description']
                    content_date?: parameters['rowFilter.things.content_date']
                    created_at?: parameters['rowFilter.things.created_at']
                    updated_at?: parameters['rowFilter.things.updated_at']
                    deleted_at?: parameters['rowFilter.things.deleted_at']
                    external_id?: parameters['rowFilter.things.external_id']
                    type?: parameters['rowFilter.things.type']
                    external_source?: parameters['rowFilter.things.external_source']
                }
                body: {
                    /** things */
                    things?: definitions['things']
                }
                header: {
                    /** Preference */
                    Prefer?: parameters['preferReturn']
                }
            }
            responses: {
                /** No Content */
                204: never
            }
        }
    }
}

export interface definitions {
    things: {
        /**
         * Note:
         * This is a Primary Key.<pk/>
         */
        id?: string
        image_url?: string
        external_url?: string
        title?: string
        description?: string
        content_date?: string
        created_at?: string
        updated_at?: string
        deleted_at?: string
        external_id?: string
        type: string
        external_source: string
    }
}

export interface parameters {
    /** Preference */
    preferParams: 'params=single-object'
    /** Preference */
    preferReturn: 'return=representation' | 'return=minimal' | 'return=none'
    /** Preference */
    preferCount: 'count=none'
    /** Filtering Columns */
    select: string
    /** On Conflict */
    on_conflict: string
    /** Ordering */
    order: string
    /** Limiting and Pagination */
    range: string
    /** Limiting and Pagination */
    rangeUnit: string
    /** Limiting and Pagination */
    offset: string
    /** Limiting and Pagination */
    limit: string
    /** things */
    'body.things': definitions['things']
    'rowFilter.things.id': string
    'rowFilter.things.image_url': string
    'rowFilter.things.external_url': string
    'rowFilter.things.title': string
    'rowFilter.things.description': string
    'rowFilter.things.content_date': string
    'rowFilter.things.created_at': string
    'rowFilter.things.updated_at': string
    'rowFilter.things.deleted_at': string
    'rowFilter.things.external_id': string
    'rowFilter.things.type': string
    'rowFilter.things.external_source': string
}

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface operations {}

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface external {}
