name: Poll Foursquare

on:
  schedule:
    - cron: "*/2 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Poll
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl --request POST -url https://ryancheung.com/api/poll/foursquare

